export default [
    {
        name: 'c',
        logo: 'c.png',
        color: 'white',
        xp: '5 y.o.',
        level: 40,
    },
    {
        name: 'css',
        logo: 'css.svg',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 15,
    },
    {
        name: 'dart',
        logo: 'dart.svg',
        color: 'white',
        xp: '5 y.o.',
        level: 20,
    },
    {
        name: 'docker',
        logo: 'docker.svg',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 25,
    },
    {
        name: 'dotnet',
        logo: 'dotnet.png',
        color: '#9900F0',
        xp: '5 y.o.',
        level: 30,
    },
    {
        name: 'expressjs',
        logo: 'expressjs.png',
        color: 'gray',
        xp: '5 y.o.',
        level: 35,
    },
    {
        name: 'figma',
        logo: 'figma.svg',
        color: 'white',
        xp: '5 y.o.',
        level: 40,
    },
    {
        name: 'flutter',
        logo: 'flutter.svg',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 45,
    },
    {
        name: 'git',
        logo: 'git.png',
        color: 'orange',
        xp: '5 y.o.',
        level: 50,
    },
    {
        name: 'go',
        logo: 'go.png',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 55,
    },
    {
        name: 'html',
        logo: 'html.png',
        color: '#ff9d00',
        xp: '5 y.o.',
        level: 60,
    },
    {
        name: 'java',
        logo: 'java.svg',
        color: 'red',
        xp: '5 y.o.',
        level: 65,
    },
    {
        name: 'javascript',
        logo: 'javascript.svg',
        color: '#ebeb04',
        xp: '5 y.o.',
        level: 70,
    },
    {
        name: 'mongodb',
        logo: 'mongodb.png',
        color: 'green',
        xp: '5 y.o.',
        level: 75,
    },
    {
        name: 'mysql',
        logo: 'mysql.svg',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 80,
    },
    {
        name: 'nodejs',
        logo: 'nodejs.svg',
        color: 'green',
        xp: '5 y.o.',
        level: 85,
    },
    {
        name: 'nuxtjs',
        logo: 'nuxtjs.svg',
        color: 'teal',
        xp: '5 y.o.',
        level: 90,
    },
    {
        name: 'php',
        logo: 'php.png',
        color: '#ad7df7',
        xp: '5 y.o.',
        level: 95,
    },
    {
        name: 'python',
        logo: 'python.png',
        color: 'yellow',
        xp: '5 y.o.',
        level: 100,
    },
    {
        name: 'reactjs',
        logo: 'reactjs.svg',
        color: 'royalblue',
        xp: '5 y.o.',
        level: 105,
    },
    {
        name: 'rollup',
        logo: 'rollup.svg',
        color: '#ff002f',
        xp: '5 y.o.',
        level: 110,
    },
    {
        name: 'sass',
        logo: 'sass.svg',
        color: '#fd4967',
        xp: '5 y.o.',
        level: 115,
    },
    {
        name: 'sequelize',
        logo: 'sequelize.png',
        color: 'skyblue',
        xp: '5 y.o.',
        level: 120,
    },
    {
        name: 'springboot',
        logo: 'springboot.svg',
        color: 'green',
        xp: '5 y.o.',
        level: 125,
    },
    {
        name: 'strapi',
        logo: 'strapi.svg',
        color: 'blue',
        xp: '5 y.o.',
        level: 130,
    },
    {
        name: 'svelte',
        logo: 'svelte.svg',
        color: 'orange',
        xp: '5 y.o.',
        level: 135,
    },
    {
        name: 'typeorm',
        logo: 'typeorm.png',
        color: 'orange',
        xp: '5 y.o.',
        level: 140,
    },
    {
        name: 'typescript',
        logo: 'typescript.svg',
        color: 'blue',
        xp: '5 y.o.',
        level: 145,
    },
    {
        name: 'vitejs',
        logo: 'vitejs.svg',
        color: 'purple',
        xp: '5 y.o.',
        level: 150,
    },
    {
        name: 'vuejs',
        logo: 'vuejs.svg',
        color: 'teal',
        xp: '5 y.o.',
        level: 155,
    },
    {
        name: 'websocket',
        logo: 'websocket.png',
        color: 'white',
        xp: '5 y.o.',
        level: 160,
    },
]
